"""init schema

Revision ID: a932afee4b12
Revises: 
Create Date: 2025-12-19 03:31:19.563400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'a932afee4b12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('profiles',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('profile_key', sa.String(length=64), nullable=False),
    sa.Column('focus_config_json', sa.UnicodeText(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profile_key', name='uq_profiles_user_profilekey')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_index('ix_profiles_user_profilekey', 'profiles', ['user_id', 'profile_key'], unique=False)
    op.create_table('runs',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('profile_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params_json', sa.UnicodeText(), nullable=True),
    sa.Column('summary_path', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_profile_id'), 'runs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    op.create_table('url_pool',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('profile_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'url_hash', name='uq_url_pool_profile_urlhash')
    )
    op.create_index(op.f('ix_url_pool_profile_id'), 'url_pool', ['profile_id'], unique=False)
    op.create_index('ix_url_pool_profile_urlhash', 'url_pool', ['profile_id', 'url_hash'], unique=False)
    op.create_table('run_items',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('run_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=40), nullable=False),
    sa.Column('job_source', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('llm_score', sa.Integer(), nullable=True),
    sa.Column('bucket', sa.String(length=64), nullable=True),
    sa.Column('output_dir', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'url_hash', name='uq_run_items_run_urlhash')
    )
    op.create_index(op.f('ix_run_items_run_id'), 'run_items', ['run_id'], unique=False)
    op.create_index('ix_run_items_run_urlhash', 'run_items', ['run_id', 'url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_items_run_urlhash', table_name='run_items')
    op.drop_index(op.f('ix_run_items_run_id'), table_name='run_items')
    op.drop_table('run_items')
    op.drop_index('ix_url_pool_profile_urlhash', table_name='url_pool')
    op.drop_index(op.f('ix_url_pool_profile_id'), table_name='url_pool')
    op.drop_table('url_pool')
    op.drop_index(op.f('ix_runs_user_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_profile_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index('ix_profiles_user_profilekey', table_name='profiles')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
