#!/usr/bin/env bash
# usage: ./scripts/slice_report.sh <slice-id> [base-ref]
#
# Generates tasks/<slice-id>.report.md. Everything under FACTS is computed from git
# and ci/gate.py, so it cannot be misreported. The executing agent fills in only the
# NARRATIVE fields -- the parts that need a mind.
#
# See docs/AGENT-WORKFLOW.md section 3.
set -uo pipefail

SLICE="${1:?usage: slice_report.sh <slice-id> [base-ref]}"
BASE="${2:-main}"

# The slice id is interpolated into two paths, one of which is written to. Without a
# guard, `slice_report.sh ../../etc/whatever` resolves outside tasks/ and the script
# would happily create a file there. Restrict it to the shape a slice id actually has.
case "$SLICE" in
  *[!a-zA-Z0-9._-]* | "" | .* )
    echo "invalid slice id: '$SLICE' (allowed: letters, digits, . _ - ; must not start with '.')" >&2
    exit 2
    ;;
esac

TASK="tasks/${SLICE}.md"
OUT="tasks/${SLICE}.report.md"
[ -f "$TASK" ] || { echo "missing $TASK"; exit 1; }

# Prefer the venv interpreter so this behaves the same from a shell and from CI.
PY=".venv/bin/python"
[ -x "$PY" ] || PY="python"

ALLOW=$(awk '/^```allowlist$/{f=1;next} /^```$/{f=0} f' "$TASK" | sed '/^$/d')
CHANGED=$(git diff --name-only "$BASE"...HEAD)

{
  echo "# ${SLICE} — report"
  echo
  echo "<!-- FACTS: generated by scripts/slice_report.sh. Do not edit. -->"
  echo "## FACTS"
  echo
  echo "Base \`$BASE\` · Head \`$(git rev-parse --short HEAD)\` · $(date -u +%FT%TZ)"
  echo
  echo '### Ratchet gate'
  echo '```'
  "$PY" ci/gate.py 2>&1 | tail -25
  echo '```'
  echo
  echo '### Baseline delta'
  echo '```'
  git diff "$BASE"...HEAD -- ci/baseline.json | grep -E '^[+-] *"' || echo '(baseline unchanged)'
  echo '```'
  echo
  echo '### Diffstat'
  echo '```'
  git diff --stat "$BASE"...HEAD | tail -30
  echo '```'
  echo
  echo '### Scope check'
  VIOL=0
  while read -r f; do
    [ -z "$f" ] && continue
    grep -Fxq "$f" <<<"$ALLOW" || { echo "- OUT OF SCOPE: \`$f\`"; VIOL=1; }
  done <<<"$CHANGED"
  [ "$VIOL" -eq 0 ] && echo "- all changed files are within the allowlist"
  echo
  echo '### tests/ untouched'
  if git diff --name-only "$BASE"...HEAD -- tests/ | grep -q .; then
    echo '- **VIOLATION** tests/ was modified:'
    git diff --name-only "$BASE"...HEAD -- tests/ | sed 's/^/  - /'
  else
    echo '- confirmed: no changes under tests/'
  fi
  echo
  echo '### Module size'
  echo '```'
  wc -l app/fastapi_run.py 2>/dev/null
  echo '```'
  echo
  echo "<!-- NARRATIVE: filled in by the executing agent. -->"
  cat <<'EOF'
## NARRATIVE

### Decisions taken that were not in the brief

### Stop-and-ask conditions hit

### Slack banked or left on the table
(if gate.py reported slack and the baseline was not lowered, say why)

### Problems noticed but NOT fixed (per Forbidden)

### Left undone
EOF
} > "$OUT"
echo "wrote $OUT"
